### PR TITLE
Improve rest api paths for likenft queries

### PR DESCRIPTION
**Pull request by elise-ng**
Ref oursky/likecoin-chain#275

One question, would you prefer:
- `/classes/by_iscn/{iscn_id_prefix}` and `/classes/by_account/{account}` or
- `/iscn-classes/{iscn_id_prefix}` and `/account-classes/{account}`?

### CODE REVIEW

**Comment by hochiw** [comment]
don't really have a strong preference but I guess `/iscn-classes/{iscn_id_prefix}` and `/account-classes/{account}` looks better

**Comment by rickmak** [comment]
Let do `/iscn-classes/{iscn_id_prefix}` and `/account-classes/{account}`

Since we won't have use-case for returning all Classes, making the inheritance appear in the API is not wise.

**Comment by chihimng** [comment]
updated

**Comment by chihimng** [comment]
on second thought we could also do `/iscn/{iscn id}/classes` and `/account/{addr}/classes`

currently for the reverse query it's `/classes/{class id}/iscn` and `classes/{class id}/account`

**Pull request merged**
