### PR TITLE
LaiChiKok Upgrade (v2.0.0)

### PR DESCRIPTION
**Pull request by chihimng**
## Changelog
- Upgrade cosmos-sdk to 0.44.8, ibc-go to 2.1.0
- Add support for `like` account prefix (by LikerLand)
- Add migrations for bech32 stored in state (by LikerLand)
- Add `liked debug convert-prefix` command tool for bech32 conversion

## Testing Done
- Add test cases for dual prefix interoperability at x/bank and x/iscn
- Add test cases for ibc ics-20 transfer
- Execute bech32 store migrations with mainnet snapshot and inspected output
- Test full upgrade flow with mainnet snapshot and asserted invariants
- Query post-upgrade state based on mainnet snapshot and inspected grpc / cli responses

## Known Issues
- CLI and REST query to x/gov proposer, deposits and votes of inactive proposals will return addresses in old prefix. To be handled in subsequent patch. Note the REST endpoint is deprecated. (oursky/likecoin-chain#182)

### CODE REVIEW

**Comment by chihimng** [comment]
@hochiw please see if i missed anything?

**Comment by rickmak** [comment]
lgtm.

**Comment by rickmak** [comment]
last but not least, we forgot to update CHANGELOG.md

**Comment by rickmak** [comment]
Sent at https://github.com/likecoin/likecoin-chain/pull/68

**Pull request closed without merging**
