### PR TITLE
Dep(#298): Add tests for buy and sell

### PR DESCRIPTION
**Pull request by elise-ng**
Ref oursky/likecoin-chain#285 
Depends on oursky/likecoin-chain#298 

- Add tests for BuyNFT msg server
- Add tests for SellNFT msg server

Note buy and sell already covered by e2e tests in previous prs

### CODE REVIEW

**Comment by rickmak** [comment]
Should send PR to nft branch?

**Comment by chihimng** [comment]
> Should send PR to nft branch?

oops

**Comment by chihimng** [comment]
no idea why tests failed, it passed locally and on subsequent pr....

**Comment by hochiw** [comment]
> no idea why tests failed, it passed locally and on subsequent pr....

@chihimng  weird, maybe try rebase?

**Review by hochiw — APPROVED** [review]

**Pull request merged**
