### PR TITLE
Implement kv store, query and mutation for claimable nft content

### PR DESCRIPTION
**Pull request by elise-ng**
Ref oursky/likecoin-chain#202 (part 2 of 3)

- scaffold kv store and basic queries
- implement keeper get claimables by class + test case
- implement query claimables by class + test case
- implement create, update and delete mutations
- implement cli

testing done:
- tested CRUD manually via cli

### CODE REVIEW

**Comment by hochiw** [comment]
oh F didn't know claimable nft would be a different type

**Comment by chihimng** [comment]
i originally thought we can just store everything in a nice array, then i realized it probably can't take 1000s ~~arrows in the knee~~ entries at once

and the entry is not actually minted nft but content, might need better naming 🤔

**Comment by hochiw** [comment]
since i am working on claiming I probably will need to rebase on this pr 🤔

**Review by hochiw — APPROVED** [review]

**Comment by hochiw** [comment]
Will merge via #224

**Comment by hochiw** [comment]
merge first cos error registration conflict

**Pull request merged**
